### ISSUE TITLE
运行npm run server时报错

### ISSUE THREAD

**Issue by xjdata** [NatureFeng/generator-react-component-gen#3]
你好，我是前端菜鸟，按照说明进行安装 最后一步运行  run  server报错，不知道是哪里错了。谢谢。

```
> node server.js --server

module.js:338
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\web\fis\server.js:1:77)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! cn-imxin@0.0.1 server: `node server.js --server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cn-imxin@0.0.1 server script 'node server.js --server'.
npm ERR! This is most likely a problem with the cn-imxin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --server
npm ERR! You can get their info via:
npm ERR!     npm owner ls cn-imxin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\web\fis\npm-debug.log
```

我看有提示说找不到模块 webpack 于是 `npm install webpack -g` 安装倒是成功了 但是有个提醒
`npm WARN optional dep failed, continuing fsevents@1.0.1`

**Comment by NatureFeng** [comment]
npm install webpack 看看，不要加 -g
